### ISSUE TITLE
Problems installing NGSpeciesID

### ISSUE THREAD

**Issue by PKuperus** [ksahlin/NGSpeciesID#10]
Hi,

We really would like to test and use your program, but we encounter some problems with installing it. It seems like the same problem that 2tony2 mentioned. So we tried his suggestion and installed (with sudo apt) m4, autoconf, automake, libtool. Unfortunately it still doesn't work.
We run it on ubuntu 20.05 (fully updated), with miniconda. Running on Win10-WSL. 

Could you maybe help us out?

kind regards,
Peter

The error message is copy-pasted below:

```
pip install NGSpeciesID
Collecting NGSpeciesID
  Using cached NGSpeciesID-0.1.1.1-py2.py3-none-any.whl
Collecting parasail==1.1.11
  Using cached parasail-1.1.11.tar.gz (46 kB)
Collecting edlib>=1.1.2
  Using cached edlib-1.3.8.post2-cp36-cp36m-manylinux2010_x86_64.whl (304 kB)
Requirement already satisfied: numpy in ./miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages (from parasail==1.1.11->NGSpeciesID) (1.16.1)
Building wheels for collected packages: parasail
  Building wheel for parasail (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/data/miniconda3/envs/NGSpeciesID/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-26r5hzgx
       cwd: /tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/
  Complete output (264 lines):
  running bdist_wheel
  parasail/libparasail.so not found, attempting to build
  Downloading latest parasail master
  Unzipping parasail master archive
  fixing executable bits after unzipping
  Unable to find parasail configure script
  Prepending /usr/bin to PATH
  PATH=/usr/bin:/home/data/miniconda3/envs/NGSpeciesID/bin:/home/data/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2021.222.0_x64__79rhkp1fndgsc:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files (x86)/Pulse Secure/VC142.CRT/X64:/mnt/c/Program Files (x86)/Pulse Secure/VC142.CRT/X86:/mnt/c/Users/NanoPore Data2/AppData/Local/Microsoft/WindowsApps:/snap/bin
  Running autoreconf -fi from ./parasail-master
  b'This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi'
  b'm4 (GNU M4) 1.4.18'
  b'autoconf (GNU Autoconf) 2.69'
  b'automake (GNU automake) 1.16.1'
  b'libtool (GNU libtool) 2.4.6'
  b'autoreconf (GNU Autoconf) 2.69'
  libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
  libtoolize: copying file 'build-aux/ltmain.sh'
  libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
  libtoolize: copying file 'm4/libtool.m4'
  libtoolize: copying file 'm4/ltoptions.m4'
  libtoolize: copying file 'm4/ltsugar.m4'
  libtoolize: copying file 'm4/ltversion.m4'
  libtoolize: copying file 'm4/lt~obsolete.m4'
  configure.ac:115: installing 'build-aux/compile'
  configure.ac:74: installing 'build-aux/config.guess'
  configure.ac:74: installing 'build-aux/config.sub'
  configure.ac:66: installing 'build-aux/install-sh'
  configure.ac:66: installing 'build-aux/missing'
  Makefile.am: installing 'build-aux/depcomp'
  parallel-tests: installing 'build-aux/test-driver'
  autoreconf -fi exited with return code 0
  configuring parasail in directory ./parasail-master
  checking whether make supports nested variables... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... no
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  configure:
  configure: C compiler
  configure:
  checking whether make supports the include directive... no
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking dependency style of gcc... none
  checking for gcc option to accept ISO C99... none needed
  checking for C compiler vendor... gnu
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for C compiler version... 9.3.0
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking malloc.h usability... yes
  checking malloc.h presence... yes
  checking for malloc.h... yes
  checking poll.h usability... yes
  checking poll.h presence... yes
  checking for poll.h... yes
  checking for unistd.h... (cached) yes
  checking windows.h usability... no
  checking windows.h presence... no
  checking for windows.h... no
  checking sys/mman.h usability... yes
  checking sys/mman.h presence... yes
  checking for sys/mman.h... yes
  checking whether byte ordering is bigendian... no
  checking for an ANSI C-conforming const... yes
  checking for inline... inline
  checking for C/C++ restrict keyword... __restrict
  checking size of int... 4
  checking for struct __stat64... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking for int8_t... yes
  checking for int16_t... yes
  checking for int32_t... yes
  checking for int64_t... yes
  checking for uint8_t... yes
  checking for uint16_t... yes
  checking for uint32_t... yes
  checking for uint64_t... yes
  checking for off_t... yes
  checking for size_t... yes
  checking for OpenMP flag of C compiler... -fopenmp
  checking for SSE2 support... default
  checking for SSE2 _mm_set1_epi64x... yes
  checking for SSE2 _mm_set_epi64x... yes
  checking for SSE4.1 support... -msse4.1
  checking for SSE4.1 _mm_insert_epi64... yes
  checking for SSE4.1 _mm_extract_epi64... yes
  checking for AVX2 support... -mavx2
  checking for AVX2 _mm256_set1_epi64x... yes
  checking for AVX2 _mm256_set_epi64x... yes
  checking for AVX2 _mm256_insert_epi64... yes
  checking for AVX2 _mm256_insert_epi32... yes
  checking for AVX2 _mm256_insert_epi16... yes
  checking for AVX2 _mm256_insert_epi8... yes
  checking for AVX2 _mm256_extract_epi64... yes
  checking for AVX2 _mm256_extract_epi32... yes
  checking for AVX2 _mm256_extract_epi16... yes
  checking for AVX2 _mm256_extract_epi8... yes
  checking for AVX512F support... -mavx512f
  checking for AVX512BW support... -mavx512bw
  checking for AVX512VBMI support... -mavx512vbmi
  checking for xgetbv... yes
  checking for AltiVec support... no
  checking for ARM NEON support... no
  checking whether C compiler accepts -fopenmp-simd... yes
  checking for _aligned_malloc... no
  checking for aligned_alloc... yes
  checking for filelength... no
  checking for memalign... yes
  checking for memset... yes
  checking for poll... yes
  checking for posix_memalign... yes
  checking for getopt... yes
  checking for SetUnhandledExceptionFilter... no
  checking for _fstat64... no
  checking for _stat64... no
  checking for int64_t literal suffix... LL
  checking for GetSystemTimeAsFileTime... no
  checking for clock_get_time... no
  checking for library containing clock_gettime... none required
  checking for clock_gettime CLOCK_MONOTONIC... yes
  checking for clock_gettime CLOCK_REALTIME... yes
  checking for library containing sqrt... -lm
  checking zlib.h usability... no
  checking zlib.h presence... no
  checking for zlib.h... no
  checking for library containing gzopen... no
  checking for grep that handles long lines and -e... (cached) /usr/bin/grep
  checking whether C compiler supports visibility flag... -fvisibility=hidden
  configure:
  configure: C++ compiler
  configure:
  checking for g++... no
  checking for c++... no
  checking for gpp... no
  checking for aCC... no
  checking for CC... no
  checking for cxx... no
  checking for cc++... no
  checking for cl.exe... no
  checking for FCC... no
  checking for KCC... no
  checking for RCC... no
  checking for xlC_r... no
  checking for xlC... no
  checking whether we are using the GNU C++ compiler... no
  checking whether g++ accepts -g... no
  checking dependency style of g++... none
  checking for C++ compiler vendor... unknown
  checking for C++ compiler version...
  checking for OpenMP flag of C++ compiler... unknown
  checking for variadic macros... no
  configure:
  configure: Libtool setup
  configure:
  checking how to print strings... printf
  checking for a sed that does not truncate output... (cached) /usr/bin/sed
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /usr/bin/dd
  checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... no
  checking our pkgconfig libname... parasail-1
  checking our pkgconfig version... 2.4.3
  checking our pkgconfig_libdir... ${libdir}/pkgconfig
  expanded our pkgconfig_libdir... /usr/local/lib/pkgconfig
  checking our pkgconfig_libfile... parasail-1.pc
  checking our package / suffix... Pairwise Sequence Alignment Library /
  checking our pkgconfig description... Pairwise Sequence Alignment Library
  checking our pkgconfig requires...
  checking our pkgconfig ext libs... -lparasail
  checking our pkgconfig cppflags...
  checking our pkgconfig ldflags...
  noninstalled pkgconfig -L /tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/parasail-master/src/.libs
  noninstalled pkgconfig -I /tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/parasail-master/.
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating config.h
  config.status: executing depfiles commands
  config.status: error: in `/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/parasail-master':
  config.status: error: Something went wrong bootstrapping makefile fragments
      for automatic dependency tracking.  Try re-running configure with the
      '--disable-dependency-tracking' option to at least be able to build
      the package (albeit without support for automatic dependency tracking).
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py", line 447, in <module>
      install_requires=INSTALL_REQUIRES,
    File "/home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py", line 409, in run
      prepare_shared_lib()
    File "/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py", line 403, in prepare_shared_lib
      build_parasail(libname)
    File "/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py", line 308, in build_parasail
      raise RuntimeError("configure failed")
  RuntimeError: configure failed
  ----------------------------------------
  ERROR: Failed building wheel for parasail
  Running setup.py clean for parasail
Failed to build parasail
Installing collected packages: parasail, edlib, NGSpeciesID
  Attempting uninstall: parasail
    Found existing installation: parasail 1.2.4
    Uninstalling parasail-1.2.4:
      Successfully uninstalled parasail-1.2.4
    Running setup.py install for parasail ... error
    ERROR: Command errored out with exit status 1:
     command: /home/data/miniconda3/envs/NGSpeciesID/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j3wa47lc/install-record.txt --single-version-externally-managed --compile --install-headers /home/data/miniconda3/envs/NGSpeciesID/include/python3.6m/parasail
         cwd: /tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/
    Complete output (8 lines):
    running install
    parasail/libparasail.so not found, attempting to build
    Archive 'parasail-master.zip' already downloaded
    Archive 'parasail-master.zip' already unzipped to /tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e
    parasail archive executable permissions ok
    parasail already configured in directory ./parasail-master
    making parasail
    error: [Errno 2] No such file or directory: 'make': 'make'
    ----------------------------------------
  Rolling back uninstall of parasail
  Moving to /home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages/parasail-1.2.4.dist-info/
   from /home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages/~arasail-1.2.4.dist-info
  Moving to /home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages/parasail/
   from /home/data/miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages/~arasail
ERROR: Command errored out with exit status 1: /home/data/miniconda3/envs/NGSpeciesID/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cpvf0dwr/parasail_8994b80cbe3e4c9aade6bdf54850a90e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j3wa47lc/install-record.txt --single-version-externally-managed --compile --install-headers /home/data/miniconda3/envs/NGSpeciesID/include/python3.6m/parasail Check the logs for full command output.
```

**Comment by ksahlin** [comment]
Hi @PKuperus,

Thanks for reporting! The key line in the error message seems to be 

`error: [Errno 2] No such file or directory: 'make': 'make'`.

You can install make by `apt-get -y install make` or `sudo apt-get install build-essential` (I took this answer from [here](https://askubuntu.com/questions/161104/how-do-i-install-make)).

after installing `make` see if it works and let me know. 

I will in the meantime have a look at what makes `parasail` cause this trouble.

Best,
K

**Comment by ksahlin** [comment]
The `build-essential` builds other things as well which you might need for parasail, so if `apt-get -y install make` does not do it, maybe the heat weight `build-essential` will. 

I was also looking at more recent issues on the parasail repository, and observed this one: https://github.com/jeffdaily/parasail/issues/87. Where it is suggested to run `sudo apt update; sudo apt install autoconf automake libtool`. Let me know how it goes.

**Comment by PKuperus** [comment]
thank you! I will try now.

...ill start with sudo apt-get install build-essential

**Comment by PKuperus** [comment]
great, I think "sudo apt-get install build-essential" worked...but still an error, as far as I understand the error...something with a incompatibl new version of pysam==0.15.2

pip install NGSpeciesID
Collecting NGSpeciesID
  Using cached NGSpeciesID-0.1.1.1-py2.py3-none-any.whl
Collecting parasail==1.1.11
  Using cached parasail-1.1.11.tar.gz (46 kB)
Collecting edlib>=1.1.2
  Using cached edlib-1.3.8.post2-cp36-cp36m-manylinux2010_x86_64.whl (304 kB)
Requirement already satisfied: numpy in ./miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages (from parasail==1.1.11->NGSpeciesID) (1.16.1)
Building wheels for collected packages: parasail
  Building wheel for parasail (setup.py) ... done
  Created wheel for parasail: filename=parasail-1.1.11-py2.py3-none-linux_x86_64.whl size=13863996 sha256=e7b2077b7f532626a11eb40b6cf43f37a7484887357cb32041618a2ddc1a87ed
  Stored in directory: /home/data/.cache/pip/wheels/86/9f/57/e4b92eb9286a92d9e461327be0860a7d531bcadce88ec9871c
Successfully built parasail
Installing collected packages: parasail, edlib, NGSpeciesID
  Attempting uninstall: parasail
    Found existing installation: parasail 1.2.4
    Uninstalling parasail-1.2.4:
      Successfully uninstalled parasail-1.2.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
medaka 0.11.5 requires pysam==0.15.2, but you have pysam 0.16.0.1 which is incompatible.
Successfully installed NGSpeciesID-0.1.1.1 edlib-1.3.8.post2 parasail-1.1.11

**Comment by ksahlin** [comment]
Ok good. Could you try removing the conda environment you previously set up for `NGSpeciesID` completely (with the erroneous parasail) and then do a fresh install?

```
conda deactivate NGSpeciesID
conda env remove --name NGSpeciesID
// then install from scratch
```

**Comment by ksahlin** [comment]
The problem seems to be that you have some other program in your environment using a newer version of pysam. Creating a new environment in conda for NGSpeciesID and not installing any other software using pysam in this specific conda environment should hopefully fix this.

**Comment by PKuperus** [comment]
Okay:
conda deactivate NGSpeciesID
conda env remove --name NGSpeciesID

conda create -n NGSpeciesID python=3.6 pip
conda activate NGSpeciesID
conda install --yes -c conda-forge -c bioconda medaka=0.11.5 openblas==0.3.3 spoa racon minimap2
pip install NGSpeciesID

To bad!  the pysam0.16.0.1 is still there

error:
pip install NGSpeciesID
Collecting NGSpeciesID
  Using cached NGSpeciesID-0.1.1.1-py2.py3-none-any.whl
Collecting parasail==1.1.11
  Using cached parasail-1.1.11-py2.py3-none-linux_x86_64.whl
Collecting edlib>=1.1.2
  Using cached edlib-1.3.8.post2-cp36-cp36m-manylinux2010_x86_64.whl (304 kB)
Requirement already satisfied: numpy in ./miniconda3/envs/NGSpeciesID/lib/python3.6/site-packages (from parasail==1.1.11->NGSpeciesID) (1.16.1)
Installing collected packages: parasail, edlib, NGSpeciesID
  Attempting uninstall: parasail
    Found existing installation: parasail 1.2.4
    Uninstalling parasail-1.2.4:
      Successfully uninstalled parasail-1.2.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
medaka 0.11.5 requires pysam==0.15.2, but you have pysam 0.16.0.1 which is incompatible.
Successfully installed NGSpeciesID-0.1.1.1 edlib-1.3.8.post2 parasail-1.1.11

**Comment by ksahlin** [comment]
Ok, I will look into this soon.

Reading from the log, it seems that you have  `NGSpeciesID` installed now (just not the medaka module). In that case,  `NGSpeciesID` can be run with `racon` instead of `medaka` for polishing. This is specified with:

```
NGSpeciesID --ont --consensus --racon --racon_iter 3 --fastq [reads.fastq] --outfolder [/path/to/output] 
```

**Comment by PKuperus** [comment]
Thank you so much for your help! 

...and about the pysam0.16.0.1 thingy...
When I installed NGSpecieID on our second computer I noticed that pysam 0.16.0.1 gets installed during the execution of the "conda install --yes -c conda-forge -c bioconda medaka=0.11.5 openblas==0.3.3 spoa racon minimap2" command!

kind regards,
Peter

**Comment by ksahlin** [comment]
Probably solved with new installation instructions as of 2025-04-19: https://github.com/ksahlin/NGSpeciesID?tab=readme-ov-file#installation
